### ISSUE TITLE
Warning:when I train the model, I meet this warning. Can you tell me  the reason? thanks a lot

### ISSUE THREAD

**Issue by ga546** [CityU-AIM-Group/SIGMA#21]
![image](https://user-images.githubusercontent.com/82253048/202881314-f5034712-4e08-4e1d-9185-274b8c0adeeb.png)

**Comment by ga546** [comment]
> ![image](https://user-images.githubusercontent.com/82253048/202881314-f5034712-4e08-4e1d-9185-274b8c0adeeb.png)

there are so many ,so i consider whether it affect the training.

**Comment by wymanCV** [comment]
Hi, this warning is caused by the spectral clustering algorithm in updating the memory bank. The reason may lie in the random initialization at the training start and different sklearn versions.

It will not have some influence on the performance of our experiments. Nevertheless, if you train the model end-to-end, it is better to turn it off by setting a False at the following position.

https://github.com/CityU-AIM-Group/SIGMA/blob/9e2c33b48f6bb2bf40a7d21468157ec4012b08c6/configs/SIGMA/sigma_vgg16_cityscapace_to_foggy.yaml#L42

**Comment by ga546** [comment]
> Hi, this warning is caused by the spectral clustering algorithm in updating the memory bank. The reason may lie in the random initialization at the training start and different sklearn versions.
> 
> It will not have some influence on the performance of our experiments. Nevertheless, if you train the model end-to-end, it is better to turn it off by setting a False at the following position.
> 
> https://github.com/CityU-AIM-Group/SIGMA/blob/9e2c33b48f6bb2bf40a7d21468157ec4012b08c6/configs/SIGMA/sigma_vgg16_cityscapace_to_foggy.yaml#L42

ok, I will try it! Thanks for you quick reply
