### ISSUE TITLE
Hello again, I was trying to train on another machine and i keep getting this error. can you help please? kind regards

### ISSUE THREAD

**Issue by astuweb** [CityU-AIM-Group/SIGMA#4]
![ts1](https://user-images.githubusercontent.com/50729468/167302193-08d80aaa-035a-400c-88e2-dd2b46c308dc.png)

**Comment by wymanCV** [comment]
This issue seems to be related to the tensorboard, which won't affect the training. We just added the tensorborad api for the convenience of our research and we didn't face such an issue. 

You can try to disable tensorbord logging by adding --use_tensorboar False in your training scripts (more details can be found in tools/train_net_da.py) to address this issue.

**Comment by astuweb** [comment]
Yes right I was also looking at this  https://github.com/tensorflow/tensorboard/issues/1976 and the issue is resolved thanks.  but during the training it start evaluating  in every 5 iterations. is it how it works?

**Comment by wymanCV** [comment]
you can try to change SOLVER.VAL_ITER in the YAML config file. We set validation every 100 iterations to find benchmark results as other DAOD works.

**Comment by astuweb** [comment]
okay thanks I will try it.
