### ISSUE TITLE
Some Random Thoughts

### ISSUE THREAD

**Issue by michaelku1** [CityU-AIM-Group/SIGMA#42]
I personally get your frustration as I think the cityscapes to foggy cityscapes adaptation is hard to achieve good semantic alignment on due to the amount of noise that distorts the semantic features.

**Comment by wymanCV** [comment]
Hi, thanks for your interest.
I think the fluctuation is more likely caused by the EMP baseline since the multi-level adversarial learning seems to have a more obvious influence on the pixel-level object detector. We found that the phenomenon can be relieved from three aspects: reducing the learning rate, training enough iterations, and using Style-GAN-generated data.

**Comment by michaelku1** [comment]
I see. So I guess it's just minor tuning. Thanks for your insights.
