### ISSUE TITLE
Question about VOC2Watercolor & Comic

### ISSUE THREAD

**Issue by GingerCohle** [CityU-AIM-Group/SIGMA#51]
Thank you for your excellent work. I notice that in your configs/sigma_plus_plus/pascal_to_watercolor_res101_da.yaml. The weight is pascal_to_water_model_57_mAP.pth. To achieve this result, do I need to train from  scratch like "catalog://ImageNetPretrained/MSRA/R-101" or train based on #'./published_models/source_only_pascal_to_water_comic.pth'? 
![image](https://github.com/CityU-AIM-Group/SIGMA/assets/37873318/332041f1-77f5-4124-b93d-0a02dd68e654)

**Comment by GingerCohle** [comment]
By the way, does ./published_models/source_only_pascal_to_water_comic.pth' can be pretrained moedel for DA_pascal_to_water?

**Comment by wymanCV** [comment]
Hi, thanks for your interest!

We use the source-only model to initialize the Pascial-related experiments. Since the watercolor and comic share the same class setting, the source-only model (pre-trained on Pascal VOC) is the same. Sorry for some wrong code comments that I forgot to correct.

Moreover, I have provided the required source-only models to make it easier to run experiments.

**Comment by wymanCV** [comment]
@GingerCohle  Hi, considering the instability of FCOS on Pascal-related settings, I just also uploaded the log files for your reference [here](https://portland-my.sharepoint.com/:f:/g/personal/wuyangli2-c_my_cityu_edu_hk/ErOVYBNqVMNGsoi0BFrO07cBK0pTptJwxUrT8GNeQxF8jQ?e=qFQ6Ai).

**Comment by GingerCohle** [comment]
Thank you for your continual supporting!!!
