### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by geekyutao** [CityU-AIM-Group/SIGMA#7]
Hi, amazing work! I followed the step-by-step installation instruction but met the following error. Do you have any ideas about this? Did I miss modify something? Thank you!

2022-05-11 21:08:26,489 fcos_core.trainer INFO: Start training
DA_ON: True
2022-05-11 21:10:25,284 fcos_core.trainer INFO: eta: 6 days, 20:56:49  iter: 20  loss_ds: 6.1977 (6.9134)  node_loss: 2.0234 (2.0159)  mat_loss_aff: 0.0991 (0.0992)  mat_loss_qu: 0.0005 (0.0005)  loss_cls: 0.6540 (0.7507)  loss_reg: 1.3081 (1.9726)  loss_centerness: 0.6631 (0.6738)  loss_adv_P7: 0.2785 (0.2792)  loss_adv_P6: 0.2755 (0.2747)  loss_adv_P5: 0.2736 (0.2740)  loss_adv_P4: 0.2750 (0.2750)  loss_adv_P3: 0.2762 (0.2762)  time: 4.4850 (5.9393)  data: 0.0478 (1.7929)  dis_loss: 0.0604 (0.0615)  lr_backbone: 0.000833  lr_middle_head: 0.001667  lr_fcos: 0.000833  lr_dis: 0.000833  max mem: 10271
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
Segmentation fault (core dumped)

**Comment by wymanCV** [comment]
Hi, thanks. I think you have installed this project correctly since you can train the model. I  just tried searching about it and found this [one](https://github.com/awslabs/autogluon/issues/1020), which seems to be related to CPU. 

I am not sure weather you can solve this by setting WITH_CLUSTER_UPDATE (in the YAML file) False as we implement the spectral clustering algorithm with KNN on CPU. If it can work, you can reset it True and tune the n_job in the "update_seed" function of graph_matching_head. (n_job=-1 will use all CPU cores in parallel)

**Comment by geekyutao** [comment]
Thank you for the tips! I turned off WITH_CLUSTER_UPDATE and the issue has been solved. This was likely caused by insufficient CPU cores.
